### ISSUE TITLE
Bulk import

### ISSUE THREAD

**Issue by theolampert** [Alexeykhr/flashcard-new-tab#5]
Would you accept a pull request to allow pasting in bulk csv-like text?

A quick and dirty console script I was using to import a list:
```js
const words = `
question1;answer2
question2;answer2
`;

words.split('\n').map(word => word.split(';')).forEach(pair => {
  $('#h-action-create').click()
  $('#card-question-input').value = pair[0]
  $('#card-answer-input').value = pair[1]
  $('button[type="submit"]').click()
})
```

But ideally there would be a field somewhere in the deck settings to do this properly.

**Comment by Alexeykhr** [comment]
Hi, I personally don’t use this extension myself, and I don’t like the design either: D

Therefore, thanks, but there is no point in wasting time on this repository :)
